[package]
name = "chip-8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
env_logger = "0.10.2"
rand = "0.8.5"
sdl2 = "0.36.0"
clap = { version = "4.4.18", features = ["derive"] }
